var quotes = [
  "Thank you! All is great!",
"Fun & helpful instruction",
"I really liked the collaboration / role play",
"Group work was great! Good intro!",
"Lots of fun with the group work. Great way to learn",
"Engaging course. Good examples",
"Very hands-on and interactive course! Fun exercises!",
"Group work; historical recipes as a fun example; slow pace that let us try things on our own",
"Really liked the pace :) Very instructive",
"Good pace, and attention to explaining the very basics of what we do",
"Thank You! Very thorough introduction to Python programming and plotting. I hope a workshop that builds on this course will be offered! :)",
"The instructors are extremely nice and understanding. Thank you!",
"Very clear, good tips, resources are excellent",
"Good intro, but the time constraints on how much you could cover were unfortunate",
"Good and clear explanations and nice speed to follow for beginners",
"Great structure, informative, fun! I had been here before but I learnt new things!",
"Very nice and helpful, even for non-students. I do not feel ignored in this class!",
"Time management was great; smooth sessions; great trouble shooting of helpers; less students :)",
"Nicely paced and well conducted workshop",
"The level was good - nice to feel I could keep up + even try extra commands",
"This is very useful and practical course. I hope to have the second level of the python course to learn more. Thanks the teachers!",
"Good to follow the steps; easy set-up; good help if needed",
"Made the threshold to start using git much lower. most was easy to understand. nice atmosphere :)",
"Great course! :) The best thing was that it was very practical and hands-on",
"I really enjoyed the hands-on and simple to do exercises. You always learn more by getting a demonstration and then trying yourself. :)",
"The post-its work well. Friendly tutors! Good teaching materials.",
"Interactive + collaborative exercises :)",
"Both instructors were very nice and helpful",
"The basics of Git were well explained and introduced.",
"Really nice and helpful instructors :)",
"A very good introduction to Git!! Very useful.",
"Nice pace to the introdcution, easy to follow + informative. Thanks for the pa[ir]ing, helps to see the flow!",
"The course was great!",
"Nice pace. Understandable. Thank you",
"I understood git (finally!) Thank you!",
"Great that lesson is divided into smaller parts. makes it more understandable",
"Keep up the good work!",
"I like the step by step learning process with simple examples.",
"Learn new language",
"Very useful with many helpers that walk around!",
"Good pace + easy to follow / understand!",
"I like that its very relevant to data analysis, and they are the kind of things I would use it for -> making figures etc.",
"From scratch and very easy to follow.",
"Great atmosphere",
"Good instructors!",
"Good course!!! with step by step instructions",
"Good instructors. Good setup / Anaconda etc.",
"Nice teachers",
"Very positive with help and sticky notes, thank you great course!",
"Good",
"Lots of help available!",
"Possible to follow the speed and concrete tasks not just teaching the code",
"Very organized. Very good lecture and methodology",
"Passe tempo",
"Differences b/w MATLAB & Python & C++ [???] indexing",
"Informative. Learned a lot.",
"Clear explanations, good rythm at the end of the first period (before lunch)",
"Liked visualizing data w/ the plot functions. Have never done that before",
"Easy to follow",
"Very good communication days before the course. Pace of the course",
"Pro: import libraries, plotting",
"Looking forward for more workshops",
"Course topics well designed to understandbasic usage of functions on Python",
"Good pace and visualisation",
"Easy to understand examples",
"Mostly good to follow",
"Good explained",
"Great!",
"Good examples",
"More course like this will be appreciated! Thanks!",
"Very useful, great with hands-on exercises :)",
"Wonderful course, definitely worth it, and I am glad I came. Learned a lot! I like the theory about how it works combined with trying myself =)",
"Great course, will be useful in future certainly!",
"The history-window for the bash commands was great + I managed to follow, understand + catch up!",
"Good pace!",
"Very useful!",
"I like that you showed different things",
"Very nice class! It would have been nice to test git in different contexts. (modifying python file, review of an article in word...) But you did cover a bit that. So I am happy :)",
"Nice pace, you understood when it was a bit too fast and then slowed down. I managed to follow everything even if I didn't take the first course. (The command history would be very useful in both parts of the course)",
"Very good course. I have now a much better understanding of R-Studio",
"Great teachers. Would love more workshops on workflow, good coding style, tidyverse/tidydata, functions, github",
"Nice that we could go through it at the same time",
"Nice overview of the many possiblities you have with R",
"Thanks for organizing this, we appreaciate it indeed",
"Veldig fint at navnene/forkortelsene forklares, f. eks. at 'c' står for combine. Takk for lærerikt kurs :)",
"Very good and informative! Please have more workshops.",
"Nice course, thanks!",
"Very good approach from very simple datasets to the more complex ones :)",
"Good explanations",
"Great workshop! Very nice presenters and helpful material."
];

//document.getElementById('quoteDisplay').style.fontFamily = "comic sans ms";
//Change the font of the quotes. Put this in the function below. Tested and works.

function newQuote() {
  var randomNumber = Math.floor(Math.random() * (quotes.length));
  document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
  document.getElementById('quoteDisplay').style.fontFamily = "comic sans ms";
  document.getElementById('quoteDisplay').style.fontSize = "46px";
}
